version: "3.9"

services:
  aled.sqlserver:
    container_name: Aled.SqlServer
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - MSSQL_USER=sa
      - MSSQL_SA_PASSWORD=2C6A9EE7-FE9E-4A79-BD4C-80C8C484B149
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  aled.redis:
    container_name: Aled.Redis
    image: redis:latest
    ports:
      - "6379:6379"

  aled.noSql:
    container_name: Aled.NoSql
    image: mongo:latest
    ports:
      - "27017:27017"
    
  ngrok:
    container_name: Aled.Ngrok
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - "4040:4040"