// This file is automatically generated by ABP framework to use MVC Controllers from CSharp

using System.Threading.Tasks;
using Aled.OpenFoodFactService.Products.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace Aled.OpenFoodFactService.Products;

public interface IProductAppService : IApplicationService
{
    Task<ProductDto> GetAsync(GetProductDto getProductDto);
}