// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Aled.OpenFoodFactService.Products;
using Aled.OpenFoodFactService.Products.Dtos;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace Aled.OpenFoodFactService.Products;

public interface IProductAppService : IApplicationService
{
    Task<ProductDto> GetAsync(GetProductDto getProductDto);
}
