// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Aled.OpenFoodFactService.Products;
using Aled.OpenFoodFactService.Products.Dtos;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Aled.OpenFoodFactService.Products;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IProductAppService), typeof(ProductClientProxy))]
public partial class ProductClientProxy : ClientProxyBase<IProductAppService>, IProductAppService
{
    public virtual async Task<ProductDto> GetAsync(GetProductDto getProductDto)
    {
        return await RequestAsync<ProductDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetProductDto), getProductDto }
        });
    }
}
