// This file is automatically generated by ABP framework to use MVC Controllers from CSharp

using System.Threading.Tasks;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace Aled.OpenFoodFactService;

public interface IHealthCheckAppService : IApplicationService
{
    Task<string> CheckAsync();
}