// This file is automatically generated by ABP framework to use MVC Controllers from CSharp

using Volo.Abp.Application.Dtos;

// ReSharper disable once CheckNamespace
namespace Aled.OpenFoodFactService.Products.Dtos;

public class GetProductDto : EntityDto
{
    public string Code { get; set; }
}