// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Aled.OpenFoodFactService.Products.Dtos;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Aled.OpenFoodFactService.Products.Dtos;

public class ProductDetailsDto : EntityDto
{
    public string ProductName { get; set; }

    public string Brands { get; set; }

    public string IngredientsText { get; set; }

    public string Allergens { get; set; }

    public string ImageFrontUrl { get; set; }

    public string[] CategoryTags { get; set; }

    public string IngredientsOrigins { get; set; }

    public string Manufacturing { get; set; }

    public string Packaging { get; set; }

    public string Quantity { get; set; }

    public int NovaGroup { get; set; }

    public NutrientLevelsDto NutrientLevels { get; set; }

    public string Nutriscore { get; set; }

    public NutrientsDto Nutrients { get; set; }

    public VitaminsDto Vitamins { get; set; }

    public VitaminsDto GetVitamins()
    {
        return new VitaminsDto
        {
            B1 = Nutrients.B1,
            B2 = Nutrients.B2,
            B6 = Nutrients.B6,
            B12 = Nutrients.B12,
            C = Nutrients.C,
        };
    }
}
