// This file is automatically generated by ABP framework to use MVC Controllers from CSharp

using System;
using Volo.Abp.Application.Dtos;

// ReSharper disable once CheckNamespace
namespace Aled.OpenFoodFactService.Products.Dtos;

public class ProductDto : EntityDto<Guid>
{
    public string Code { get; set; }

    public ProductDetailsDto ProductDetails { get; set; }
}