// This file is automatically generated by ABP framework to use MVC Controllers from CSharp

using Volo.Abp.Application.Dtos;

// ReSharper disable once CheckNamespace
namespace Aled.OpenFoodFactService.Products.Dtos;

public class ProductDetailsDto : EntityDto
{
    public string ProductName { get; set; }

    public string Brands { get; set; }

    public string IngredientsText { get; set; }

    public string Allergens { get; set; }

    public string ImageFrontUrl { get; set; }
}