// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Aled.OpenFoodFactService.Products.Dtos;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace Aled.OpenFoodFactService.Products.Dtos;

public class VitaminsDto
{
    public double B1 { get; set; }

    public double B2 { get; set; }

    public double B6 { get; set; }

    public double B12 { get; set; }
}
